CREATE TABLE user (
    int INTEGER PRIMARY KEY AUTOINCREMENT,
    email VARCHAR(254) UNIQUE,
    name VARCHAR(128) NOT NULL
);
CREATE TABLE item (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    userid INTEGER NOT NULL,
    title VARCHAR(128) NOT NULL,
    created DATETIME NOT NULL,
    due DATETIME NOT NULL,
    done BIT NOT NULL,
    FOREIGN KEY(userid) REFERENCES user(id)
);